"""add documents table

Revision ID: 7c4020728880
Revises: 7d34ee1843a2
Create Date: 2025-10-22 15:56:18.584774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7c4020728880'
down_revision: Union[str, Sequence[str], None] = '7d34ee1843a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('book_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_documents_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_book_id'), 'documents', ['book_id'], unique=False)
    op.create_index('ix_documents_content_text', 'documents', ['content_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_content_text', table_name='documents')
    op.drop_index(op.f('ix_documents_book_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
